### ISSUE TITLE
Adapt to WildCo folder structure

### ISSUE THREAD

**Issue by wildcole** [WildCoLab/WildCo_Collaboration_Data_Extractor#1]
@ChrisBeirne @tazarve I think there is a need to tweak the code for our folder structure where  camera checks are nested within stations?

**Comment by tazarve** [comment]
> @ChrisBeirne @tazarve I think there is a need to tweak the code for our folder structure where camera checks are nested within stations?

sounds good. I just did this for Itcha. I can upload this modification (a few extra lines of code)

**Comment by tazarve** [comment]
sounds good. I just did this for Itcha. I can upload this modification (a few extra lines of code)

**Comment by ChrisBeirne** [comment]
Yes please! If you could modify it that would be great!
